### ISSUE TITLE
og:image meta tag not generated correctly with img_path

### ISSUE THREAD

**Issue by joshjohanning** [cotes2020/jekyll-theme-chirpy#754]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

## Describe the bug

It looks like the image post works when using `img_path` (ie: using the short path), but the `og:image` meta tag doesn't render correctly.

See my example [post](https://josh-ops.com/posts/using-github-checks-api/).

The title image shows up correctly in the post, but because I am using `img_path`, it doesn't seem that the `og:image` tag renders correctly. 

Markdown:

```md
img_path: /assets/screenshots/2022-10-12-using-github-checks-api
image:
  path: status-check.gif
```

If searching the source of the page, you will find:

```html
<meta property="og:image" content="https://josh-ops.com/status-check.gif" />
```

The image should be:
```
https://josh-ops.com/assets/screenshots/2022-10-12-using-github-checks-api/status-check.gif
```

At least according to the docs, this _should_ work:

> In addition, the `[img_path](https://chirpy.cotes.page/posts/write-a-new-post/#image-path)` can also be passed to the preview image, that is, when it has been set, the attribute path only needs the image file name.

### To Reproduce

1. Use `img_path`
2. Use short version of image for the post's image
3. Search html to find the `og:image` tag

### Expected behavior

Using correct version of image path

### Screenshots

n/a

### Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |         |
| `gem -v`                          |         |
| `bundle -v`                       |         |
| `bundle exec jekyll -v`           |         |
| `bundle info jekyll-theme-chirpy` |         |

### Desktop

macOS latest
Chrome latest

### Smartphone

n/a

### Additional context

cc https://github.com/joshjohanning/joshjohanning.github.io/issues/21 and credits to @ruzickap

**Comment by cotes2020** [comment]
Thanks for the report!  The `twitter:image` in `<head>` will also be missing `img_path`.

**Comment by joshjohanning** [comment]
Hi @cotes2020! I deployed this update, but it still looks like the issue persists?  My source still looking like this:

```html
<meta property="twitter:image" content="https://josh-ops.com/status-check.gif" />
<meta property="og:image" content="https://josh-ops.com/status-check.gif" />
```

I'm not using a CDN, which differs from what you're using in your instance, I believe.

From this line: https://github.com/cotes2020/jekyll-theme-chirpy/blob/4a1856310e233013c21b323a7f06c1b3279599b8/_includes/head.html#L25 


if I remove `site.img_cdn and` so that the line is now:

```html
  {% if seo_tags contains 'og:image' %}

```

then it works:

```html
<meta property="og:image" content="http://localhost:4000/assets/screenshots/2022-10-12-using-github-checks-api/status-check.gif" />
<meta property="twitter:image" content="http://localhost:4000/assets/screenshots/2022-10-12-using-github-checks-api/status-check.gif" />
```

This also worked

```html
  {% if site.img_cdn != empty and seo_tags contains 'og:image' %}
```

Not really an expert in this, so not sure what the intent is with `site.img_cdn` here 😄

**Comment by joshjohanning** [comment]
Woot! It works, and even works on Twitter :) 

![image](https://user-images.githubusercontent.com/19912012/202256813-a2588b7a-342c-498d-9853-89ff772b3f9d.png)

**Comment by joshjohanning** [comment]
@cotes2020 okay maybe one minor thing left here that I noticed investigating my source:

![image](https://user-images.githubusercontent.com/19912012/202257250-2549e780-64f0-4b50-ad5c-f09ec47edae8.png)

```
image":{"width":"100%","height":"100%","alt":"Example of Status Checks in a Pull Request","url":"https://josh-ops.com/status-check.gif","@type":"imageObject"},"
```

It looks like there is one last reference to the `site.baseurl/page.img_path` pathing in the source.  Not sure what this one might be used for, but I think that's the last hold out.

**Comment by cotes2020** [comment]
https://github.com/cotes2020/jekyll-theme-chirpy/blob/59b5562487bc815f82b8cd7cf3b5ed58ff5e5c2a/_includes/head.html#L43

The above code can generate the correct URL no matter whether `site.baseurl` is assigned or not.

> ... I wasn't expecting to see a reference to an unreachable image in the above snippet.
> 
> ```
> https://josh-ops.com/status-check.gif
> ```
> 
> when it should be
> 
> ```
> https://josh-ops.com/assets/screenshots/2022-10-12-using-github-checks-api/status-check.gif
> ```

Now I don't quite understand what you mean. Are you getting an incomplete URL path after testing 59b5562487bc815f82b8cd7cf3b5ed58ff5e5c2a? If yes, please list the specific configuration: What are the values of `site.baseurl`, `site.img_cdn`, `page.img_path` respectively?

**Comment by joshjohanning** [comment]
Yes, I applied 59b5562487bc815f82b8cd7cf3b5ed58ff5e5c2a, and that fixed the `og:image` and `twitter:image`.

However, go to my post: https://josh-ops.com/posts/using-github-checks-api/

If you right click and view the source, you'll find a similar issue with the image:
```
"url":"https://josh-ops.com/status-check.gif","@type":"imageObject"}
```

This is in the `@context` tag
Here's a quick video of what I mean. The first two results have the correct path of the image, per the patch in 59b5562487bc815f82b8cd7cf3b5ed58ff5e5c2a. But the third result has the incorrect path for the post image.

https://user-images.githubusercontent.com/19912012/202302474-e2824c02-daae-4e6f-ae8b-65ed3a88368e.mov

So, I think there is one more thing that needs to be patched to _fully_ fix this.

**Comment by cotes2020** [comment]
Like those SEO-related `meta` tags, the content inside `<script type="application/ld+json">...</script>` is also generated by the SEO plugin.

https://github.com/cotes2020/jekyll-theme-chirpy/blob/59b5562487bc815f82b8cd7cf3b5ed58ff5e5c2a/jekyll-theme-chirpy.gemspec#L31

Will fix it soon, thanks for the video demo. 👍

**Comment by joshjohanning** [comment]
Ahhh - so actually, this made it worse for me, because I don't have a `/` at the end of my `img_path`

So now it renders as:
```
https://josh-ops.com/assets/screenshots/2022-10-12-using-github-checks-apistatus-check.gif
```

When it should be:
```
https://josh-ops.com/assets/screenshots/2022-10-12-using-github-checks-api/status-check.gif
```

I can fix this though - should I just plan to put a `/` at the end of my `img_path` property's in my posts? 

```diff
- img_path: /assets/screenshots/2022-10-12-using-github-checks-api
+ img_path: /assets/screenshots/2022-10-12-using-github-checks-api/
```

I think the logic here https://github.com/cotes2020/jekyll-theme-chirpy/commit/59b5562487bc815f82b8cd7cf3b5ed58ff5e5c2a was slightly more robust, but now that I know how it works I am good with the solution of appending a `/`.  Your docs have the `/` at the end, too. 

Thanks for all of the debugging 🎉

**Comment by cotes2020** [comment]
By now, `img_path` should end with `/`. Maybe some improvements will be added in the future to support it without forward slash.

**Comment by joshjohanning** [comment]
> By now, `img_path` should end with `/`. Maybe some improvements will be added in the future to support it without forward slash.

Works for me, thank you for confirming! 

Is there a way to update the post for something like this without modifying the "updated" time ?

**Comment by joshjohanning** [comment]
Woot! It's all fixed now with https://github.com/cotes2020/jekyll-theme-chirpy/commit/da7d7e25b6638af1b2ca4623ce3e62af039da360 😄  🎉   Thanks @cotes2020!!
