### ISSUE TITLE
How add different meta descriptions on every pages.

### ISSUE THREAD

**Issue by Nexus-Gits** [cotes2020/jekyll-theme-chirpy#863]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description
How add different meta descriptions on every pages. Singe home page description add in every pages. which make duplicate meta description error & it,s also bad for site seo.

**Comment by cotes2020** [comment]
It can be done by adding `description` in the page's front matter.
